name: GeZhouBa 6th Senior School
markdown: redcarpet
pygments: true
permalink: pretty

timezone: Asia/Shanghai
encoding: utf-8

# Site info
title: GeZhouBa 6th Seniro School
description: A memory for our youth